apiVersion: v1
kind: Pod
metadata:
  name: django-app-pod
  labels:
    name: django-app
spec:
  containers:
    - name: django
      image: acostyle/django_app
      ports:
        - containerPort: 80
      env:
      - name: SECRET_KEY
        value: "REPLACE_ME"
      - name: DEBUG
        value: "FALSE"
      - name: DATABASE_URL
        value: "postgres://uzcwlckh:6eh2CLBYfjyj4rZryJbuEsAl29du6pSt@surus.db.elephantsql.com/uzcwlckh"
      - name: ALLOWED_HOSTS
        value: "127.0.0.1,localhost"
